const PATH_API_V1 = {
  auth: {
    root: '/v1/auth',
    feature: {
      login: 'login',
      logout: 'logout',
      generateOTP: 'generateOTP',
      createSessionRegister: 'createSessionRegister',
      confirmRegister: 'confirmRegister',
      createSessionResetPassword: 'createSessionResetPassword',
      confirmOTPResetPassword: 'confirmOTPResetPassword',
      confirmResetPassword: 'confirmResetPassword',
      refreshAccessToken: 'refreshAccessToken',
    },
  },
  city: {
    root: '/v1/city',
    feature: {
      getAllCities: 'getAllCities',
      getAllDistricts: 'getAllDistricts',
      getAllWards: 'getAllWards',
    },
  },
  chat: {
    root: '/v1/chat',
    feature: {
      createChat: 'create',
      getByIdChat: 'getById',
      getAllChats: 'getAll',
      searchChat: 'search',
      updateByIdChat: 'update',
      deleteByIdChat: 'delete',
    },
  },
  user: '/v1/user',
  blog: '/v1/blog',
  admin: '/v1/admin',
  brand: '/v1/brand',
  order: '/v1/order',
  rating: '/v1/rating',
  coupon: {
    root: '/v1/coupon',
    feature: {
      createCoupon: 'create',
      getByIdCoupon: 'getById',
      getAllCoupons: 'getAll',
      searchCoupon: 'search',
      updateByIdCoupon: 'update',
      deleteByIdCoupon: 'delete',
    },
  },
  demand: {
    root: '/v1/demand',
    feature: {
      createDemand: 'create',
      getByIdDemand: 'getById',
      getAllDemands: 'getAll',
      searchDemand: 'search',
      updateByIdDemand: 'update',
      deleteByIdDemand: 'delete',
    },
  },
  account: '/v1/account',
  payment: '/v1/payment',
  setting: '/v1/setting',
  product: '/v1/product',
  customer: '/v1/customer',
  discount: '/v1/discount',
  question: '/v1/question',
  wishlist: '/v1/wishlist',
  inventory: '/v1/inventory',
  dashboard: '/v1/dashboard',
  blogCategory: '/v1/blogCategory',
  productCategory: '/v1/productCategory',
  productCategoryGroup: '/v1/productCategoryGroup',
};

export default PATH_API_V1;
