const express = require('express');
const router = express.Router();

const authRouter = require('./auth.route');
const blogRouter = require('./blog.route');
const cartRouter = require('./cart.route');
const userRouter = require('./user.route');
const cityRouter = require('./city.route');
const chatRouter = require('./chat.route');
const adminRouter = require('./admin.route');
const brandRouter = require('./brand.route');
const orderRouter = require('./order.route');
const demandRouter = require('./demand.route');
const ratingRouter = require('./rating.route');
const couponRouter = require('./coupon.route');
const commentRouter = require('./comment.route');
const productRouter = require('./product.route');
const discountRouter = require('./discount.route');
const wishlistRouter = require('./wishlist.route');
const inventoryRouter = require('./inventory.route');
const notificationRouter = require('./notification.route');
const blogCategoryRouter = require('./blogCategory.route');
const SpecificationRouter = require('./specification.route');
const productCategoryRouter = require('./productCategory.route');
const productCategoryGroupRouter = require('./productCategoryGroup.route');

router.use('/api/v1/auth', authRouter);
router.use('/api/v1/user', userRouter);
router.use('/api/v1/blog', blogRouter);
router.use('/api/v1/city', cityRouter);
router.use('/api/v1/cart', cartRouter);
router.use('/api/v1/chat', chatRouter);
router.use('/api/v1/order', orderRouter);
router.use('/api/v1/admin', adminRouter);
router.use('/api/v1/brand', brandRouter);
router.use('/api/v1/demand', demandRouter);
router.use('/api/v1/rating', ratingRouter);
router.use('/api/v1/coupon', couponRouter);
router.use('/api/v1/product', productRouter);
router.use('/api/v1/comment', commentRouter);
router.use('/api/v1/wishlist', wishlistRouter);
router.use('/api/v1/discount', discountRouter);
router.use('/api/v1/inventory', inventoryRouter);
router.use('/api/v1/blogCategory', blogCategoryRouter);
router.use('/api/v1/notification', notificationRouter);
router.use('/api/v1/specification', SpecificationRouter);
router.use('/api/v1/productCategory', productCategoryRouter);
router.use('/api/v1/productCategoryGroup', productCategoryGroupRouter);

module.exports = router;
