const PATH_ADMIN = {
  admin: "admin",
  user: "user",
  blog: "blog",
  brand: "brand",
  order: "order",
  demand: "demand",
  rating: "rating",
  coupon: "coupon",
  account: "account",
  payment: "payment",
  setting: "setting",
  product: "product",
  customer: "customer",
  discount: "discount",
  question: "question",
  wishlist: "wishlist",
  inventory: "inventory",
  dashboard: "dashboard",
  blogCategory: "blogCategory",
  productCategory: "productCategory",
  productCategoryGroup: "productCategoryGroup",
};
export default PATH_ADMIN;
