const PATH_API_V1 = {
  auth: {
    mainPath: "/v1/auth",
    feature: {
      login: "/login",
      logout: "/logout",
      generateOTP: "/generateOTP",
      createSessionRegister: "/createSessionRegister",
      confirmRegister: "/confirmRegister",
      createSessionResetPassword: "/createSessionResetPassword",
      confirmOTPResetPassword: "/confirmOTPResetPassword",
      confirmResetPassword: "/confirmResetPassword",
      refreshAccessToken: "/refreshAccessToken",
    },
  },
  user: "/v1/user",
  blog: "/v1/blog",
  admin: "/v1/admin",
  brand: "/v1/brand",
  order: "/v1/order",
  rating: "/v1/rating",
  coupon: "/v1/coupon",
  demand: "/v1/demand",
  account: "/v1/account",
  payment: "/v1/payment",
  setting: "/v1/setting",
  product: "/v1/product",
  customer: "/v1/customer",
  discount: "/v1/discount",
  question: "/v1/question",
  wishlist: "/v1/wishlist",
  inventory: "/v1/inventory",
  dashboard: "/v1/dashboard",
  blogCategory: "/v1/blogCategory",
  productCategory: "/v1/productCategory",
  productCategoryGroup: "/v1/productCategoryGroup",
};

export default PATH_API_V1;
