const PATH_USER = {
  home: "",
  OTP:'otp',
  user: "user",
  login: "login",
  register: "register",
  brand: "brand",
  order: "order",
  rating: "rating",
  coupon: "coupon",
  account: "account",
  payment: "payment",
  product: "product",
  discount: "discount",
  question: "question",
  wishlist: "wishlist",
  forgetpassword:"forgetpassword",
  notfound: "*",
};
export default PATH_USER;
