const PATH_USER = {
  home: "",
  user: "user",
  login: "login",
  brand: "brand",
  order: "order",
  rating: "rating",
  coupon: "coupon",
  account: "account",
  payment: "payment",
  product: "product",
  discount: "discount",
  question: "question",
  wishlist: "wishlist",
  register: "register",
  Incentives:"Incentives",
  confirmOTP: "confirmOTP",
  generateOTP: "generateOTP",
  resetPassword: "resetPassword",
  notfound: "*",
};
export default PATH_USER;
